export const products = [
  {
    id: 1,
    title: 'Duch',
    images: ['/products/1-1.jpg', '/products/1-1b.jpg'], 
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 2,
    title: 'Dýně - Boo!',
    images: ['/products/1-2.jpg', '/products/1-2b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 3,
    title: 'Čarodějnice',
    images: ['/products/1-3.jpg', '/products/1-3b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 4,
    title: 'Strašidelná dýně',
    images: ['/products/1-4.jpg', '/products/1-4b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 5,
    title: 'Mumie',
    images: ['/products/1-5.jpg', '/products/1-5b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 6,
    title: 'Dýně - kočka',
    images: ['/products/1-6.jpg', '/products/1-6b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 7,
    title: 'Dýně - sladkosti',
    images: ['/products/1-7.jpg', '/products/1-7b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 8,
    title: 'Zámek',
    images: ['/products/1-8.jpg', '/products/1-8b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 9,
    title: 'Dýně - klobouk',
    images: ['/products/1-9.jpg', '/products/1-9b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 10,
    title: 'Dýně - netopír',
    images: ['/products/1-10.jpg', '/products/1-10b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 11,
    title: 'Dýně - lebka',
    images: ['/products/1-11.jpg', '/products/1-11b.jpg'],
    price: 120,
    salePrice: null,
    category: 'halloween',
    ingredients: 'Vrtulník',
  },
  {
    id: 12,
    title: 'Vozík',
    images: ['/products/2-1.jpg', '/products/2-1.jpg'],
    price: 120,
    salePrice: null,
    category: 'boys',
    ingredients: 'Vrtulník',
  },
  {
    id: 13,
    title: 'Mořská panna',
    images: ['/products/2-2.jpg', '/products/2-2.jpg'],
    price: 120,
    salePrice: null,
    category: 'girls',
    ingredients: 'Vrtulník',
  },
  {
    id: 14,
    title: 'Jednorožec s duhou',
    images: ['/products/2-3.jpg', '/products/2-3.jpg'],
    price: 120,
    salePrice: null,
    category: 'girls',
    ingredients: 'Vrtulník',
  },
  {
    id: 15,
    title: 'Jednorožec',
    images: ['/products/2-4.jpg', '/products/2-4.jpg'],
    price: 120,
    salePrice: null,
    category: 'girls',
    ingredients: 'Vrtulník',
  },
  {
    id: 16,
    title: 'Ležící jednorožec',
    images: ['/products/2-8.jpg', '/products/2-8.jpg'],
    price: 120,
    salePrice: null,
    category: 'girls',
    ingredients: 'Vrtulník',
  },
  {
    id: 17,
    title: 'Vrtulník',
    images: ['/products/2-10.jpg', '/products/2-10.jpg'],
    price: 120,
    salePrice: null,
    category: 'boys',
    ingredients: 'Vrtulník',
  },
  {
    id: 18,
    title: 'Letadlo',
    images: ['/products/2-11.jpg', '/products/2-11.jpg'],
    price: 120,
    salePrice: null,
    category: 'boys',
    ingredients: 'Vrtulník',
  },
  {
    id: 19,
    title: 'Bagr',
    images: ['/products/2-12.jpg', '/products/2-12.jpg'],
    price: 120,
    salePrice: null,
    category: 'boys',
    ingredients: 'Vrtulník',
  },
  {
    id: 20,
    title: 'Buldozer',
    images: ['/products/2-13.jpg', '/products/2-13.jpg'],
    price: 120,
    salePrice: null,
    category: 'boys',
    ingredients: 'Vrtulník',
  },
];
