export const products = [
  {
    id: 1,
    title: 'Duch',
    images: ['/products/1-1.jpg', '/products/1-1b.jpg'], 
    price: 100,
    salePrice: 89.90,
    category: 'halloween',
  },
  {
    id: 2,
    title: 'Dýně - Boo!',
    images: ['/products/1-2.jpg', '/products/1-2b.jpg'],
    price: 399,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 3,
    title: 'Čarodějnice',
    images: ['/products/1-3.jpg', '/products/1-3b.jpg'],
    price: 150,
    salePrice: 125,
    category: 'halloween',
  },
  {
    id: 4,
    title: 'Strašidelná dýně',
    images: ['/products/1-4.jpg', '/products/1-4b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 5,
    title: 'Mumie',
    images: ['/products/1-5.jpg', '/products/1-5b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 6,
    title: 'Dýně - kočka',
    images: ['/products/1-6.jpg', '/products/1-6b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 7,
    title: 'Dýně - sladkosti',
    images: ['/products/1-7.jpg', '/products/1-7b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 8,
    title: 'Zámek',
    images: ['/products/1-8.jpg', '/products/1-8b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 9,
    title: 'Dýně - klobouk',
    images: ['/products/1-9.jpg', '/products/1-9b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 10,
    title: 'Dýně - netopír',
    images: ['/products/1-10.jpg', '/products/1-10b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
  {
    id: 11,
    title: 'Dýně - lebka',
    images: ['/products/1-11.jpg', '/products/1-11b.jpg'],
    price: 200,
    salePrice: null,
    category: 'halloween',
  },
];
